### ISSUE TITLE
Doc: how to use this?

### ISSUE THREAD

**Issue by adityacs** [Wikia/kapajira#6]
Could you please give some basic docs on how to use this?

Thanks

**Comment by jcellary** [comment]
Hey! I created a short description on the wiki: https://github.com/Wikia/kapajira/wiki. Hope that will get you started, let me know if you have any more questions

**Comment by adityacs** [comment]
@jcellary Thanks. I have started using this. I will keep you posted in case of any issues.

Thanks for developing this :+1:
