### ISSUE TITLE
Error if try using module

### ISSUE THREAD

**Issue by lpopil** [Wikia/kapajira#8]
Hi, everyone! I try to use this module and have some issue:
`[cpu_alert:alert10] 2017/06/06 18:25:30 E! exec command failed: Output: Traceback (most recent call last):
  File "/home/kapajira/kapajira/bin/on_alert.py", line 7, in <module>
    from kapajira.jira.reporter import JiraReporter
  File "/usr/lib/python2.7/site-packages/kapajira-0.0.1-py2.7.egg/kapajira/jira/reporter.py", line 20
    def existing_issue(self, issue_hash: str):
                                       ^
SyntaxError: invalid syntax
: exit status 1
`
Can you help me fix this?

**Comment by pwojcik86** [comment]
Which version of Python are you using?

**Comment by lpopil** [comment]
On this case python2.7, but if i try to use python3 i have another error:
"issue type is required" - how i can set issue type?

**Comment by pwojcik86** [comment]
Right now the issue type is not configurable, and is always set to `Defect`. It's possible that your JIRA doesn't have that specific type.

**Comment by lpopil** [comment]
Need python3=)
I changed issue type to "issue_type='Task'" and it work for me.
Set this issue clossed.
Thanks for quick reply and have a nice day!
